---
title: "Generation of protein gold standard for *SignalingProfiler* 2.0 benchmarking"
author: "Veronica Venafra"
output:
  html_document:
    theme: flat
    highlight: zenburn
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

## Introduction
This workbook refers to the manuscript *SignalingProfiler 2.0: a network-based approach to bridge multi-omic data to phenotypic hallmarks*.

## Import libraries and functions

```{r message = FALSE}
source('0.libraries.R')
source('0.functions.R')
```

## Gold standard proteins

```{r}
downstream <- read_excel('./input/Gold standard.xlsx', sheet = 1, skip = 1)
reg_sub <- downstream %>%
  mutate(Regulation = ifelse(grepl('MTOR*', Regulator), Regulation*-100, Regulation*100)) %>%
  dplyr::select(Regulator, Target) %>%
  distinct()

head(reg_sub)
```

### Venn diagram MTOR and AMPK targets

```{r fig.height=5,fig.width=5, fig.align='center'}
list_venn <- list(AMPK = reg_sub$Target[reg_sub$Regulator == 'AMPKA'],
                  MTOR = reg_sub$Target[grepl('MTOR*', reg_sub$Regulator)])

venn <- Venn(list_venn)
d <- process_data(venn)
d2 <- process_data(venn)

d2@region <- st_polygonize(d@setEdge)

col <- c(AMPK = '#3B4992', MTOR = '#008B45')

ggplot() +
  geom_sf(aes(fill = name), data = venn_region(d2)) +
  geom_sf(aes(color = name), data = venn_setedge(d)) +
  #geom_sf_text(aes(label = name), data = venn_setlabel(d), size = 12) +
  geom_sf_text(aes(label = count), data = venn_region(d), size = 12) +
  scale_color_manual(values = alpha(col, .6)) +
  scale_fill_manual(values = alpha(col, .9)) +
  theme_void() +
  theme(text = element_text(size=12))+
  theme(legend.title = element_blank()) -> venn

venn
```

### Barplot of molecular functions of gold standard proteins

```{r fig.height=5,fig.width=5, fig.align='center'}

SignalingProfiler::molecular_function_annotation(reg_sub %>% rename('gene_name' = 'Target'), organism = 'human') -> reg_sub_annotated

reg_sub_annotated$mf <- factor(reg_sub_annotated$mf, levels = c('other', 'kin', 'tf'))

reg_sub_annotated <- reg_sub_annotated %>%
  mutate(Regulator =ifelse(str_detect(pattern = 'MTOR', Regulator), 'MTOR', Regulator)) %>%
  distinct() %>% group_by(gene_name, mf) %>%
  reframe(Regulator = paste0(Regulator, collapse = ';'))

target_colors <- c('AMPKA' = '#3B4992', 'MTOR' = '#008B45', 'MTOR;AMPKA' = 'darkblue')

ggplot(reg_sub_annotated, aes(x = mf)) +
  geom_bar(stat = "count", position = "stack", aes(fill = Regulator), alpha = .6) +
  geom_text(stat = 'count', aes(label = after_stat(count)),
            position = position_stack(vjust = 1.05), size = 3, color = 'black') +
  #scale_y_continuous(breaks = seq(0, 3000, by = 500)) +
  scale_fill_manual(values = target_colors) +
  theme_classic() +
  theme(text = element_text(size=10),
        axis.text.x = element_text(angle = 0, vjust = 1, size = 8),
        axis.text.y = element_text(angle = 0, hjust = 1, size = 12),
        legend.position="bottom",
        legend.title = element_blank()) +
  xlab('') +
  coord_flip()+
  ylab('N° of proteins') -> coverage_main_plot

coverage_main_plot
```
